### ISSUE TITLE
Frame Gen and Cloud Quality not detected

### ISSUE THREAD

**Issue by Mark2603** [ResetXPDR/MSFS_AutoFPS#16]
Hi,
I tried to reinstall the program several times but still it does not detect my real fps with frame gen anymore and does only show low or medium in cloud settings even if they are set to ultra, as the program only detects 30 fps instead of 60 it does ot adjust my lods. I also tried to reset my msfs settings and reinstalled framegen
[MSFS_AutoFPS20241227.log](https://github.com/user-attachments/files/18264130/MSFS_AutoFPS20241227.log)

**Comment by ResetXPDR** [comment]
Your config file is still corrupt, which was caused by the MSFS 2024 1.2.8.0 update and likely not using the installer to remove the old app before reinstalling.

Try the latest test version, which is much more robust, that you can download here: https://github.com/ResetXPDR/MSFS_AutoFPS/releases/tag/v0.4.4.2-test

As shown below, install it with the Clean Install option checked and you should be sorted.
![image](https://github.com/user-attachments/assets/0267a1f1-1ce6-43cd-8de0-30e001b42291)

Let me know how you go.

**Comment by ResetXPDR** [comment]
The instructions I have provided should fix the issue, so I am going to close this after 2 days of no response.
