### ISSUE TITLE
FPS mismatch 2024

### ISSUE THREAD

**Issue by Drums85** [ResetXPDR/MSFS_AutoFPS#6]
Hello, first and foremost I want to thank you very much for creating and updating this app as often as you do. I've been using it since almost the very beginning and have had amazing results to help me maximize my RTX4060 on my laptop to get the best visuals within the limits of my GPU. 

I updated to version 0.4.4.0 a couple days ago and everything is still working flawlessly on MSFS2020. However, in MSFS2024 it seems as if the program is not reading my FPS correctly and therefore does not make the appropriate adjustments to stay within the target FPS. I have installed the app twice now, the first time with all my previous settings and the second time as a clean install and still have the same results. I have also noticed that when MSFS2024 loses focus the app does not display as it being "on hold" and switch to "FPS settle" upon MSFS2024 regaining focus. I play on full screen mode on both 2020/2024. Is there something I am not doing correctly in 2024? 

I have included a couple screenshots of the FPS overlay that I use daily and it shows the mismatches in FPS. Thanks for your time.
![Screenshot 2024-12-19 114747](https://github.com/user-attachments/assets/558cc330-2d9a-410a-8c86-d0743a93992a)
![Screenshot 2024-12-19 114849](https://github.com/user-attachments/assets/777829e1-ea86-4a52-b025-01d56a593a81)
![Screenshot 2024-12-19 115024](https://github.com/user-attachments/assets/dd353b05-cd89-4ba7-8dcb-06e21390b557)

**Comment by ResetXPDR** [comment]
From your screenshots, it looks as though AutoFPS is showing an exact half of your actual FPS indicating that you have some sort of frame generation working in the sim that is not being detected by the app. What FG method are you using? If not the inbuilt FG, are you starting/enabling it after starting AutoFPS, because if so you need to hit the app's Reset button for it to redetect your graphics mode.

If that doesn't resolve it, send me your log file located in %appdata%\MSFS_AutoFPS\log and I'll take a look and see what's going on.

**Comment by Drums85** [comment]
Thanks for the quick response. I am using the FG built into the sim the same way I do in MSFS2020 (DLSS Quality, FG on) I have been troubleshooting the issue all morning and reading some of the other issue posts on here and started to look at the log. Upon looking around I noticed that it was detecting a Steam version of 2024. I have never owned any MSFS game in Steam or have even used the Steam app in over a year, so I thought that was very rare.

I did some looking around and there was indeed a folder in the AppData/Roaming folder that seemed to be the steam version and had a few files within it. I went ahead and deleted that folder, then restarted the simulator with AutoFPS and the log showed that it did detect the MS Store version, but I still had the same problem as before. I then saw that you have v0.4.4.1-test3 available so I did a clean install, fired up the sim again and boom now it's working just as it did for me in MSFS2020. After this flight I am currently on, I'm going to reinstall v0.4.4.0 and see if that works as normal as well and will report back. I have attached the latest log prior to me doing a clean install of v0.4.4.1-test3

Sorry for the long post, but trying to be as detailed as possible for you and if any others may encounter this rare situation.

[MSFS_AutoFPS20241219.log](https://github.com/user-attachments/files/18202801/MSFS_AutoFPS20241219.log)

**Comment by ResetXPDR** [comment]
That's great you got it going again and you are not the first person to have discovered they have ghost install of the MSFS 2024 Steam version instead of the MS Store version they actually own. I am going to modify the code so it will detect these dual installations and either work out which one to use or, if not always possible to detect, at least alert the users of the issue that they need to resolve on their end. Thanks for letting me know what you did to fix it as it is very helpful in me preventing this happen again if at all possible. On that note, I'll close this issue as resolved and continue working on a fix.

**Comment by ResetXPDR** [comment]
Some more questions to help me squash this issue. 

Did you install MSFS 2024 on the very first day it came out, as 19 Nov was the date time stamp on another user's ghost Steam MSFS 2024 version file and folders?

If you didn't permanently delete your ghost Steam MSFS 2024 version can you look in your recycle bin and tell me what files folders were there? 

FYI, the other user's ghost install files and folders looked like this?

![396694813-4c9aeea7-9f04-48cf-a4bb-21399ed16deb](https://github.com/user-attachments/assets/4402c4ec-411e-47fa-b763-5bb9d789ad07)

**Comment by Drums85** [comment]
I initially installed 2024 on 21 November. I did a full uninstall and re-install as of sometime last week and the SIM seems to be working better for me. My ghost install folder looked like that as well. Thanks so much for trying to squash it for others!

![Screenshot 2024-12-19 150622](https://github.com/user-attachments/assets/7faf4e72-f983-435e-8cc9-5e9b948f58df)

**Comment by Drums85** [comment]
v0.4.4.0 works good now as well. Thanks so much again for your assistance, cheers! 🤙🏾
